### ISSUE TITLE
Create an instance of DiscountRequest when invoices check

### ISSUE THREAD

**Issue by m-pereira** [comarev/comarev#53]
References: https://github.com/comarev/comarev/pull/54

We have this [action](https://github.com/comarev/comarev/blob/59047d343a6e810a596a89838d93f1eb6a87b30d/app/controllers/invoices_controller.rb#L28), but today if the check fails, it does not create a `DiscountRequest` instance. We need to create it even if success or failure. If failure scenario, the field `received_discount` must be 0 (zero)

**Comment by andreLumor** [comment]
Hi @m-pereira! Since #106 is blocked by #104, I was searching for other issues to work on while waiting.
What is the status of this one? I noticed it was opened a while ago.

**Comment by m-pereira** [comment]
This issue is available 😄, it's all yours lol
