### ISSUE TITLE
Improve check invoice performance

### ISSUE THREAD

**Issue by m-pereira** [comarev/comarev#66]
find company by ID only if all invoices are paid

[controller-action](https://github.com/comarev/comarev/blob/905d6448a6f925694c45b8443bdcd0037c091bbb/app/controllers/invoices_controller.rb#L30)

**Comment by tonyaraujop** [comment]
Hi there, I would like to be assign for this issue.

**Comment by m-pereira** [comment]
> Hi there, I would like to be assign for this issue.

Sure, go for it man!
