### ISSUE TITLE
Approval flow for new customers

### ISSUE THREAD

**Issue by m-pereira** [comarev/comarev#69]
Add a `self-registered` flag on the `users` table, default `false`

Implement a public signup page so that new users can register themselves. By default, the `active` field should be `false`, and the `self-registered` `true` for this flow, and a manager needs to active this new user manually.

Let's send an email to all admins notifying the newly registered user.

**Comment by rhian-cs** [comment]
Hello there! I'll be working on this issue.

**Comment by m-pereira** [comment]
Go for it @rhian-cs 🚀
