### ISSUE TITLE
Add Recovery password

### ISSUE THREAD

**Issue by m-pereira** [comarev/comarev#70]
We're using [Devise](https://github.com/heartcombo/devise), let's add the ability to recover the password.
[Recoverable](https://www.rubydoc.info/github/heartcombo/devise/master/Devise/Models/Recoverable)

**Comment by andreLumor** [comment]
Hello! I'm from the trainee program.
Can i try to resolve this issue?

**Comment by m-pereira** [comment]
> Hello! I'm from the trainee program. Can i try to resolve this issue?

Go for it man, thanks!
