### ISSUE TITLE
Fix users update route

### ISSUE THREAD

**Issue by m-pereira** [comarev/comarev#71]
A non-admin user cannot update other users, the route must return a 401 HTTP status (unauthorized) today it's returning a 500 (internal server error)

![image](https://user-images.githubusercontent.com/47258878/155757300-a28bb988-123c-4624-a7cc-8dad0879299a.png)

**Comment by ivopozzani** [comment]
Hi! May I work on this one?

**Comment by ivopozzani** [comment]
@m-pereira

**Comment by m-pereira** [comment]
> Hi! May I work on this one? @m-pereira

For sure, go for it!
