### ISSUE TITLE
Add money gem to handle invoices amout

### ISSUE THREAD

**Issue by m-pereira** [comarev/comarev#91]
**Description**

Add [money rails gem](https://github.com/RubyMoney/money-rails) to handle the currency of invoices. The column `amount` must be monetized, and the default currency needs to be `R$` ([real](https://en.wikipedia.org/wiki/Brazilian_real)).

**Comment by HeitorMC** [comment]
Hello there! I would like to be assign for this issue :fist_oncoming:

**Comment by m-pereira** [comment]
Nice, go for it!
