### ISSUE TITLE
Would it be interesting to have swagger in this project?

### ISSUE THREAD

**Issue by geeksilva97** [comarev/comarev#98]
**Description**
Add swagger to document the API.

**References**
- https://swagger.io/
-  https://github.com/rswag/rswag

**Comment by geeksilva97** [comment]
What do you think, @m-pereira ?

**Comment by m-pereira** [comment]
> What do you think, @m-pereira ?

Hey, @geeksilva97 I think it's a cool idea 👍🏻 @belgamo WDYT?

**Comment by m-pereira** [comment]
I think we can add a swagger doc for this API, but I don't like the approach of using a gem to do it based on the specs. However, since we don't have a lot of endpoints, it would be easy to start.
I'm going to start an epic that we can work on.
